apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
spec:
  limits:
  - max:
      cpu: "4880m"
      memory: "2500Mi"
    min:
      cpu: "29m"
      memory: "150Mi"
    type: Pod
  - default:
      cpu: "1"
      memory: 512Mi
    defaultRequest:
      cpu: 60m
      memory: 307Mi
    max:
      cpu: "4880m"
      memory: 2500Mi
    min:
      cpu: 29m
      memory: 150Mi
    type: Container
  - max:
      storage: 1Gi
    min:
      storage: 1Gi
    type: PersistentVolumeClaim
