---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "jenkins"
    provider: "fabric8"
    expose: "false"
  annotations:
    fabric8.io/app-menu: development
  name: "jenkins"
spec:
  type: ExternalName
  externalName: jenkins.${PROJECT_NAME}-jenkins
  ports:
  - name: http
    port: 80