spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: "WS_K8S_API_SERVER"
          value: ${WS_K8S_API_SERVER}
        - name: "K8S_API_SERVER_PROTOCOL"
          value: ${K8S_API_SERVER_PROTOCOL}
        - name: "K8S_API_SERVER_BASE_PATH"
          value: ${K8S_API_SERVER_BASE_PATH}
        - name: "OAUTH_ISSUER"
          value: ${OAUTH_ISSUER}
        - name: "OAUTH_CLIENT_ID"
          value: ${OAUTH_CLIENT_ID}
        - name: "OAUTH_SCOPE"
          value: ${OAUTH_SCOPE}
        - name: "OAUTH_AUTHORIZE_URI"
          value: ${OAUTH_AUTHORIZE_URI}
        - name: "AUTH_LOGOUT_URI"
          value: ${AUTH_LOGOUT_URI}
        - name: "FABRIC8_PIPELINES_NAMESPACE"
          value: ${FABRIC8_PIPELINES_NAMESPACE}
        - name: "PROXIED_K8S_API_SERVER"
          value: ${PROXIED_K8S_API_SERVER}
        - name: "PROXY_PASS_URL"
          value: ${PROXY_PASS_URL}
        - name: "FABRIC8_WIT_API_URL"
          value: ${FABRIC8_WIT_API_URL}
        - name: "FABRIC8_RECOMMENDER_API_URL"
          value: ${FABRIC8_RECOMMENDER_API_URL}
        - name: "FABRIC8_FORGE_API_URL"
          value: ${FABRIC8_FORGE_API_URL}
        - name: "FABRIC8_SSO_API_URL"
          value: ${FABRIC8_SSO_API_URL}
        - name: "OPENSHIFT_CONSOLE_URL"
          value: ${OPENSHIFT_CONSOLE_URL}
        image: "${fabric8-ui.image.name}:${fabric8-ui.version}"
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 10