---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/app-menu: development
  labels:
    app: "${project.artifactId}"
    provider: "fabric8"
    expose: "true"
  name: "planner"
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    app: "planner"
    provider: "fabric8"