---
apiVersion: v1
kind: Template
metadata:
  annotations:
    fabric8.io/git-commit: 0b90360981bed67ebde7b71cc6a96d34cca3dcc6
    maven.fabric8.io/app-catalog: "true"
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/zookeeper/src/main/fabric8/icon.png
    fabric8.io/git-branch: release-v2.2.168
    maven.fabric8.io/source-url: jar:file:/Users/jamesrawlings/.m2/repository/io/fabric8/online/packages/app-catalog/1.0-SNAPSHOT/app-catalog-1.0-SNAPSHOT.jar!/META-INF/fabric8/openshift.yml
  labels:
    provider: fabric8
    project: zookeeper
    version: 2.2.168
    expose: "true"
    serverId: "1"
    group: io.fabric8.ipaas.apps
  name: zookeeper
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/zookeeper/src/main/fabric8/icon.png
      fabric8.io/git-commit: 0b90360981bed67ebde7b71cc6a96d34cca3dcc6
      fabric8.io/git-branch: release-v2.2.168
    labels:
      provider: fabric8
      project: zookeeper
      version: 2.2.168
      group: io.fabric8.ipaas.apps
      expose: "true"
    name: zookeeper
  spec:
    ports:
    - name: client
      port: 2181
      targetPort: 2181
    selector:
      project: zookeeper
      provider: fabric8
      group: io.fabric8.ipaas.apps
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/zookeeper/src/main/fabric8/icon.png
      fabric8.io/git-commit: 0b90360981bed67ebde7b71cc6a96d34cca3dcc6
      fabric8.io/git-branch: release-v2.2.168
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=zookeeper&var-version=2.2.168
    labels:
      provider: fabric8
      project: zookeeper
      version: 2.2.168
      group: io.fabric8.ipaas.apps
      serverId: "1"
    name: zookeeper
  spec:
    replicas: 1
    selector:
      provider: fabric8
      project: zookeeper
      group: io.fabric8.ipaas.apps
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/zookeeper/src/main/fabric8/icon.png
          fabric8.io/git-commit: 0b90360981bed67ebde7b71cc6a96d34cca3dcc6
          fabric8.io/git-branch: release-v2.2.168
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=zookeeper&var-version=2.2.168
        labels:
          provider: fabric8
          project: zookeeper
          version: 2.2.168
          group: io.fabric8.ipaas.apps
      spec:
        containers:
        - env:
          - name: ENSEMBLE_SIZE
            value: "1"
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: fabric8/zookeeper:2.2.168
          imagePullPolicy: IfNotPresent
          name: zookeeper
          ports:
          - containerPort: 2181
            name: zkclient
          - containerPort: 8778
            name: jolokia
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
          securityContext:
            privileged: false
          volumeMounts:
          - mountPath: /opt/zookeeper/data
            name: data
            readOnly: false
          - mountPath: /opt/zookeeper/log
            name: log
            readOnly: false
        volumes:
        - emptyDir:
            medium: Memory
          name: data
        - emptyDir:
            medium: Memory
          name: log
    triggers:
    - type: ConfigChange
