---
apiVersion: v1
kind: Template
metadata:
  annotations:
    fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
    maven.fabric8.io/app-catalog: "true"
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gogs/src/main/fabric8/icon.png
    fabric8.io/git-branch: release-v2.2.303
  labels:
    provider: fabric8
    project: gogs
    repository: gogs
    scm: git
    version: 2.2.303
    expose: "true"
    group: io.fabric8.devops.apps
  name: gogs
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      provider: fabric8
      group: io.fabric8.devops.apps
      project: gogs
      repository: gogs
      scm: git
      version: 2.2.303
    name: default-gogs-git
    namespace: user-secrets-source-admin
  data:
    password: UmVkSGF0JDE=
    username: Z29nc2FkbWlu
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gogs/src/main/fabric8/icon.png
    labels:
      provider: fabric8
      group: io.fabric8.devops.apps
      project: gogs
      version: 2.2.303
    name: gogs
- apiVersion: v1
  kind: OAuthClient
  metadata:
    labels:
      provider: fabric8
      project: gogs
      version: 2.2.303
      group: io.fabric8.devops.apps
    name: gogs
  redirectURIs:
  - http://localhost:3000
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/app-menu: development
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gogs/src/main/fabric8/icon.png
      fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
      fabric8.io/git-branch: release-v2.2.303
    labels:
      provider: fabric8
      project: gogs
      version: 2.2.303
      group: io.fabric8.devops.apps
      expose: "true"
    name: gogs
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
    selector:
      project: gogs
      provider: fabric8
      group: io.fabric8.devops.apps
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gogs/src/main/fabric8/icon.png
      fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
      fabric8.io/git-branch: release-v2.2.303
    labels:
      provider: fabric8
      project: gogs
      version: 2.2.303
      group: io.fabric8.devops.apps
      expose: "true"
    name: gogs-ssh
  spec:
    ports:
    - port: 22
      protocol: TCP
      targetPort: 2222
    selector:
      project: gogs
      provider: fabric8
      group: io.fabric8.devops.apps
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: standard
    labels:
      provider: fabric8
      project: gogs
      version: 2.2.303
      group: io.fabric8.devops.apps
    name: gogs-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      provider: fabric8
      project: gogs
      version: 2.2.303
      group: io.fabric8.devops.apps
    name: fabric8-git-app-secrets
    namespace: user-secrets-source-admin
  data:
    gogs: default-git-gogs
- apiVersion: v1
  kind: ConfigMap
  metadata:
    annotations:
      fabric8.gogs/summary: '[Gogs](http://gogs/) - A self-hosted Git service written
        in Go'
      description: |
        Gogs is a self-hosted Git service written in Go.

        More details on the <a href="http://gogs.io/" target="gogs">Gogs home page</a>.
      fabric8.gogs/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gogs/src/main/fabric8/icon.png
      expose.config.fabric8.io/url-key: gogs-server--root-url
      expose.config.fabric8.io/oauth-authorize-url-key: oauth-authorize-uri
      fabric8.io/json-schema: |-
        {
          "type" : "object",
          "properties" : {
            "GOGS_SERVER__ROOT_URL" : {
              "type" : "string",
              "description" : "The root URL for the gogs server"
            },
            "DOMAIN" : {
              "type" : "string",
              "description" : "The domain name applications are installed on",
              "default" : "vagrant.f8"
            },
            "ADMIN_USER_EMAIL" : {
              "type" : "string",
              "description" : "The email address of the admin user on Gogs",
              "default" : "gogsadmin@fabric8.local"
            },
            "ADMIN_USER_PASSWORD" : {
              "type" : "string",
              "description" : "The password to login to Gogs",
              "default" : "RedHat$1"
            },
            "GOGS_SERVER__PROTOCOL" : {
              "type" : "string",
              "description" : "The protocol for gogs to use; either http or https",
              "default" : "http"
            },
            "GOGS_OAUTH_OPENSHIFT__ENABLED" : {
              "type" : "string",
              "default" : "true"
            },
            "ADMIN_USER_CREATE" : {
              "type" : "string",
              "description" : "Should we create an admin user on startup",
              "default" : "true"
            },
            "GOGS_OAUTH_OPENSHIFT__TOKEN_URL" : {
              "type" : "string"
            },
            "GOGS_OAUTH_OPENSHIFT__SCOPES" : {
              "type" : "string"
            },
            "GOGS_OAUTH_OPENSHIFT__AUTH_URL" : {
              "type" : "string"
            },
            "GOGS_WEBHOOK__TASK_INTERVAL" : {
              "type" : "string",
              "default" : "true"
            },
            "GOGS_WEBHOOK__SKIP_TLS_VERIFY" : {
              "type" : "string",
              "default" : "true"
            },
            "GOGS_SERVER__DOMAIN" : {
              "type" : "string",
              "description" : "The gogs server name",
              "default" : "gogs.vagrant.f8"
            },
            "ADMIN_USER_NAME" : {
              "type" : "string",
              "description" : "The user name to login to Gogs",
              "default" : "gogsadmin"
            },
            "GOGS_OAUTH__ENABLED" : {
              "type" : "string",
              "default" : "true"
            },
            "GOGS_OAUTH_TWITTER__ENABLED" : {
              "type" : "string",
              "default" : "false"
            },
            "KUBERNETES_ADMIN_USER" : {
              "type" : "string",
              "description" : "The default Kubernetes admin user",
              "default" : "admin"
            },
            "GOGS_OAUTH_OPENSHIFT__CLIENT_ID" : {
              "type" : "string",
              "default" : "gogs"
            }
          }
        }
    labels:
      provider: fabric8
      project: gogs
      version: 2.2.303
      group: io.fabric8.devops.apps
    name: gogs
  data:
    admin-user-create: "true"
    admin-user-email: gogsadmin@fabric8.local
    admin-user-name: gogsadmin
    admin-user-password: RedHat$1
    gogs-oauth--enabled: "true"
    gogs-oauth-openshift--auth-url: ""
    gogs-oauth-openshift--client-id: gogs
    gogs-oauth-openshift--enabled: "true"
    gogs-oauth-openshift--scopes: ""
    gogs-oauth-openshift--token-url: ""
    gogs-oauth-twitter--enabled: "false"
    gogs-server--root-url: ""
    gogs-webhook--skip-tls-verify: "true"
    gogs-webhook--task-interval: "true"
    kubernetes-admin-user: admin
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      configmap.fabric8.io/update-on-change: gogs
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gogs/src/main/fabric8/icon.png
      fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
      fabric8.io/git-branch: release-v2.2.303
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=gogs&var-version=2.2.303
    labels:
      provider: fabric8
      project: gogs
      version: 2.2.303
      group: io.fabric8.devops.apps
    name: gogs
  spec:
    replicas: 1
    selector:
      provider: fabric8
      project: gogs
      group: io.fabric8.devops.apps
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gogs/src/main/fabric8/icon.png
          fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
          configmap.fabric8.io/update-on-change: gogs
          fabric8.io/git-branch: release-v2.2.303
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=gogs&var-version=2.2.303
          pod.alpha.kubernetes.io/init-containers: '[{"image":"busybox","imagePullPolicy":"IfNotPresent","name":"init","command":["chmod","777","/app/gogs/data"],"volumeMounts":[{"mountPath":"/app/gogs/data","name":"gogs-data"}]}]'
        labels:
          provider: fabric8
          project: gogs
          version: 2.2.303
          group: io.fabric8.devops.apps
      spec:
        containers:
        - env:
          - name: GOGS_SERVER__ROOT_URL
            valueFrom:
              configMapKeyRef:
                key: gogs-server--root-url
                name: gogs
          - name: ADMIN_USER_EMAIL
            valueFrom:
              configMapKeyRef:
                key: admin-user-email
                name: gogs
          - name: ADMIN_USER_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: admin-user-password
                name: gogs
          - name: ADMIN_USER_CREATE
            value: "true"
          - name: GOGS_WEBHOOK__TASK_INTERVAL
            value: "true"
          - name: GOGS_WEBHOOK__SKIP_TLS_VERIFY
            value: "true"
          - name: ADMIN_USER_NAME
            valueFrom:
              configMapKeyRef:
                key: admin-user-name
                name: gogs
          - name: KUBERNETES_ADMIN_USER
            valueFrom:
              configMapKeyRef:
                key: kubernetes-admin-user
                name: gogs
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: fabric8/gogs:v0.9.97
          imagePullPolicy: IfNotPresent
          name: gogs
          ports:
          - containerPort: 2222
            name: ssh
          - containerPort: 3000
            name: http
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
          volumeMounts:
          - mountPath: /app/gogs/data
            name: gogs-data
        serviceAccountName: gogs
        volumes:
        - name: gogs-data
          persistentVolumeClaim:
            claimName: gogs-data
    triggers:
    - type: ConfigChange
